version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "serverless-file-processing"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-vudbwwiekb0u"
s3_prefix = "serverless-file-processing"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ApplicationName=\"serverless-file-processing\" ApiStageName=\"dev\""
