AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  serverless-file-processing
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: nodejs12.x
    CodeUri: dist/
    Timeout: 3
  
Parameters:
  ApplicationName:
    Type: String
    Default: serverless-file-processing
  ApiStageName:
    Type: String
    Default: dev

Resources:

  UnprocessedFileQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${ApplicationName}-unprocessed-file-queue

  UnprocessedFileQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties: 
      Queues: 
        - !Ref UnprocessedFileQueue
      PolicyDocument: 
        Statement: 
          - 
            Action: 
              - "SQS:SendMessage" 
            Effect: "Allow"
            Resource: !GetAtt UnprocessedFileQueue.Arn
            Principal:  
              Service: s3.amazonaws.com

  UnprocessedUpdateQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${ApplicationName}-unprocessed-update-queue

  FileBucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: !Sub ${ApplicationName}-file-bucket
      NotificationConfiguration:
        QueueConfigurations:
        - Event: 's3:ObjectCreated:*'
          Queue: !GetAtt UnprocessedFileQueue.Arn

  FileProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${ApplicationName}-file-processor-function
      Handler: fileProcessorLambda.handle
      Environment:
        Variables:
          UNPROCESSED_UPDATE_QUEUE_URL: !Ref UnprocessedUpdateQueue
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt UnprocessedUpdateQueue.QueueName
        - S3ReadPolicy:
            BucketName: !Ref FileBucket
      Events:
        UnprocessedFileEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt UnprocessedFileQueue.Arn
            BatchSize: 10
            Enabled: true

  UpdateProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${ApplicationName}-update-processor-function
      Handler: updateProcessorLambda.handle
      Events:
        UnprocessedUpdateEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt UnprocessedUpdateQueue.Arn
            BatchSize: 10
            Enabled: true

